import { describe, expect, it } from "vitest";

import {
  isAutoGeneratedUsername,
  readUsernameRejection,
  usernameUnlocksAt,
  validateUsername,
} from "./username";

describe("validateUsername", () => {
  it("accepts letters, numbers, underscores, and hyphens", () => {
    for (const name of ["jacob", "jacob_k", "jacob-k", "a1b2c3", "abc"]) {
      expect(validateUsername(name)).toBeNull();
    }
  });

  it("rejects lengths outside the API's own 3..40 bound", () => {
    expect(validateUsername("ab")).toMatch(/3 to 40/);
    expect(validateUsername("a".repeat(41))).toMatch(/3 to 40/);
    // The boundaries themselves are valid.
    expect(validateUsername("abc")).toBeNull();
    expect(validateUsername("a".repeat(40))).toBeNull();
  });

  it("rejects spaces and punctuation", () => {
    for (const name of ["has space", "slash/es", "dot.name", "emoji😀"]) {
      expect(validateUsername(name)).toMatch(/letters, numbers/);
    }
  });

  it("trims before measuring, so padding cannot fake a valid length", () => {
    expect(validateUsername("  ab  ")).toMatch(/3 to 40/);
    expect(validateUsername("  jacob  ")).toBeNull();
  });
});

describe("isAutoGeneratedUsername", () => {
  it("recognises the API's user_<8 hex> placeholder", () => {
    expect(isAutoGeneratedUsername("user_a1b2c3d4")).toBe(true);
    expect(isAutoGeneratedUsername("user_A1B2C3D4")).toBe(true);
  });

  it("leaves a chosen name alone", () => {
    for (const name of ["user_jacob", "jacob", "user_a1b2c3", "users_a1b2c3d4"]) {
      expect(isAutoGeneratedUsername(name)).toBe(false);
    }
  });
});

describe("readUsernameRejection", () => {
  const err = (status: number, message: string) =>
    Object.assign(new Error(message), { status });

  it("separates the two 409 conflicts by message", () => {
    expect(readUsernameRejection(err(409, "that username is taken"))?.kind).toBe(
      "taken"
    );
    expect(
      readUsernameRejection(err(409, "that username is not available"))?.kind
    ).toBe("reserved");
  });

  it("reads the cooldown deadline out of the 429", () => {
    const r = readUsernameRejection(
      err(429, "username can be changed again on 2026-08-14T10:00:00Z")
    );
    expect(r?.kind).toBe("cooldown");
    expect(r?.kind === "cooldown" && r.retryAt?.toISOString()).toBe(
      "2026-08-14T10:00:00.000Z"
    );
    expect(r?.message).toContain("14 August 2026");
  });

  it("survives a 429 with no parsable date", () => {
    const r = readUsernameRejection(err(429, "too many requests"));
    expect(r?.kind).toBe("cooldown");
    expect(r?.kind === "cooldown" && r.retryAt).toBeNull();
  });

  it("ignores failures that are not about the username", () => {
    expect(readUsernameRejection(err(500, "boom"))).toBeNull();
    expect(readUsernameRejection(err(0, "Network error"))).toBeNull();
    expect(readUsernameRejection(null)).toBeNull();
  });
});

describe("usernameUnlocksAt", () => {
  it("is null when the name has never been changed, so the first is free", () => {
    expect(usernameUnlocksAt(null)).toBeNull();
  });

  it("is null once the fourteen days have passed", () => {
    const old = new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString();
    expect(usernameUnlocksAt(old)).toBeNull();
  });

  it("returns the unlock date while still inside the window", () => {
    const recent = new Date(Date.now() - 1 * 24 * 60 * 60 * 1000);
    const unlock = usernameUnlocksAt(recent.toISOString());
    expect(unlock).not.toBeNull();
    // Thirteen days left, give or take the clock.
    const daysLeft = (unlock!.getTime() - Date.now()) / (24 * 60 * 60 * 1000);
    expect(daysLeft).toBeGreaterThan(12.9);
    expect(daysLeft).toBeLessThan(13.1);
  });
});
