/**
 * Username rules, shared by sign-up and settings so the two cannot drift.
 *
 * The length bounds mirror the API's own validation (3..40) so a valid form
 * cannot fail server-side on length. The character set is a client-side
 * choice: the API accepts anything in range, but a display name that can
 * hold spaces or slashes reads badly in "Good evening, <name>" and in URLs
 * later.
 *
 * Uniqueness is NOT checked here. It is enforced by a UNIQUE constraint on
 * users.username, and there is no availability endpoint to ask before
 * submitting, so a collision surfaces on write. See isUsernameTaken.
 */

export const USERNAME_MIN = 3;
export const USERNAME_MAX = 40;

const ALLOWED = /^[A-Za-z0-9_-]+$/;

/** Returns an error string, or null when the username is well formed. */
export function validateUsername(raw: string): string | null {
  const name = raw.trim();
  if (name.length < USERNAME_MIN || name.length > USERNAME_MAX) {
    return `Usernames need ${USERNAME_MIN} to ${USERNAME_MAX} characters.`;
  }
  if (!ALLOWED.test(name)) {
    return "Usernames can use letters, numbers, underscores, and hyphens.";
  }
  return null;
}

/**
 * The API auto-creates a row as `user_<first 8 of uuid>` on first
 * authenticated request. Recognising that shape is how the client knows a
 * name is still the placeholder rather than something the user chose.
 */
export function isAutoGeneratedUsername(name: string): boolean {
  return /^user_[0-9a-f]{8}$/i.test(name);
}

/** Why a username was refused, read from the API's status code. */
export type UsernameRejection =
  | { kind: "taken"; message: string }
  | { kind: "reserved"; message: string }
  | { kind: "invalid"; message: string }
  | { kind: "cooldown"; message: string; retryAt: Date | null };

/**
 * Reads a failed PATCH /v1/users/me. The API names each failure with a
 * status code (409 taken or reserved, 429 cooldown, 400 format), so this
 * branches on the code rather than on message text.
 *
 * Returns null when the failure had nothing to do with the username.
 */
export function readUsernameRejection(err: unknown): UsernameRejection | null {
  const status = (err as { status?: number })?.status;
  const raw = err instanceof Error ? err.message : "";

  if (status === 409) {
    // Both conflicts share a code; the message is what separates them.
    if (/not available/i.test(raw)) {
      return {
        kind: "reserved",
        message: "That username is not available. Try another.",
      };
    }
    return { kind: "taken", message: "That username is taken. Try another." };
  }

  if (status === 429) {
    const retryAt = parseRetryAt(raw);
    return {
      kind: "cooldown",
      message: retryAt
        ? `You changed your username recently. You can change it again on ${formatRetryDate(retryAt)}.`
        : "You changed your username recently. Try again later.",
      retryAt,
    };
  }

  if (status === 400 && /username/i.test(raw)) {
    return {
      kind: "invalid",
      message: `Usernames need ${USERNAME_MIN} to ${USERNAME_MAX} characters, using letters, numbers, underscores, and hyphens.`,
    };
  }

  return null;
}

/** The 429 carries its deadline as RFC3339 inside the message. */
function parseRetryAt(message: string): Date | null {
  const match = message.match(/\d{4}-\d{2}-\d{2}T[\d:.]+Z?/);
  if (!match) return null;
  const date = new Date(match[0]);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function formatRetryDate(date: Date): string {
  return date.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

/** How long the API makes a user wait between username changes. */
export const USERNAME_COOLDOWN_DAYS = 14;

/**
 * When the next change unlocks, or null when it is available now. Mirrors
 * the server rule: a null changed-at means the name has never been chosen,
 * so the first change is free.
 */
export function usernameUnlocksAt(
  usernameChangedAt: string | null
): Date | null {
  if (!usernameChangedAt) return null;
  const changed = new Date(usernameChangedAt);
  if (Number.isNaN(changed.getTime())) return null;
  const unlock = new Date(
    changed.getTime() + USERNAME_COOLDOWN_DAYS * 24 * 60 * 60 * 1000
  );
  return unlock.getTime() > Date.now() ? unlock : null;
}
