"use client";

import { useRouter } from "next/navigation";
import * as React from "react";
import type { User } from "@supabase/supabase-js";

import { getMe, updateMe } from "@/lib/api/users";
import { getBrowserSupabase } from "@/lib/supabase/browser";
import type { UserProfile } from "@/lib/types";
import { isAutoGeneratedUsername } from "@/lib/username";

type SessionState = {
  /** The Supabase auth user, null when signed out (or still resolving). */
  user: User | null;
  /** The Klyvi profile row (username, bio). Null until it loads. */
  profile: UserProfile | null;
  /** True until the first getSession resolves; gates flicker, not routing. */
  loading: boolean;
  /** Push a fresh profile in after Settings saves, so greetings update. */
  setProfile: (p: UserProfile) => void;
  signOut: () => Promise<void>;
};

const SessionContext = React.createContext<SessionState>({
  user: null,
  profile: null,
  loading: true,
  setProfile: () => {},
  signOut: async () => {},
});

/**
 * Owns the browser auth state and the Klyvi profile that hangs off it, so
 * any screen can greet by name without refetching. Routing decisions live
 * in proxy.ts; this context only answers who is signed in.
 */
export function AuthProvider({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const [user, setUser] = React.useState<User | null>(null);
  const [profile, setProfile] = React.useState<UserProfile | null>(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    const sb = getBrowserSupabase();
    if (!sb) {
      setLoading(false);
      return;
    }
    let cancelled = false;

    sb.auth.getSession().then(({ data }) => {
      if (cancelled) return;
      setUser(data.session?.user ?? null);
      setLoading(false);
    });

    const {
      data: { subscription },
    } = sb.auth.onAuthStateChange((_event, session) => {
      if (cancelled) return;
      setUser(session?.user ?? null);
      setLoading(false);
    });

    return () => {
      cancelled = true;
      subscription.unsubscribe();
    };
  }, []);

  // Load the Klyvi profile, and claim the username chosen at sign-up.
  //
  // The claim cannot happen on the sign-up form: there is no session yet, so
  // there is nothing to authenticate a write with. The API also auto-creates
  // the row as user_<8 hex> on the first authenticated request, so the
  // desired name is applied here, once, and only while the row still carries
  // that placeholder. A collision leaves the placeholder in place; Settings
  // is where it gets resolved.
  React.useEffect(() => {
    if (!user) {
      setProfile(null);
      return;
    }
    let cancelled = false;

    (async () => {
      let me: UserProfile;
      try {
        me = await getMe();
      } catch {
        return;
      }

      const desired = user.user_metadata?.username;
      if (
        typeof desired === "string" &&
        desired.length > 0 &&
        isAutoGeneratedUsername(me.username)
      ) {
        try {
          me = await updateMe({ username: desired });
        } catch {
          // Taken, or the write failed. Keep the placeholder rather than
          // blocking sign-in over a display name.
        }
        // Clear the request either way so it is attempted once, not on
        // every page load for the life of the account.
        const sb = getBrowserSupabase();
        await sb?.auth.updateUser({ data: { username: null } }).catch(() => {});
      }

      if (!cancelled) setProfile(me);
    })();

    return () => {
      cancelled = true;
    };
  }, [user]);

  const signOut = React.useCallback(async () => {
    const sb = getBrowserSupabase();
    if (!sb) return;
    await sb.auth.signOut();
    // The proxy sees the cleared cookie on the next navigation; go somewhere
    // public so the user does not land on a redirect.
    router.push("/");
    router.refresh();
  }, [router]);

  const value = React.useMemo(
    () => ({ user, profile, loading, setProfile, signOut }),
    [user, profile, loading, signOut]
  );

  return (
    <SessionContext.Provider value={value}>{children}</SessionContext.Provider>
  );
}

export function useSession(): SessionState {
  return React.useContext(SessionContext);
}
